### PR TITLE
add value_type to registry record

### PR DESCRIPTION
**Pull request by erral**
When testing the addon to include it in a Plone 5.2, I had to add this to be able to install it correctly.

### CODE REVIEW

**Comment by erral** [comment]
The value_type I was adding was wrong, we need a `Dict` here.

**Comment by tisto** [comment]
@erral thanks! I will have to fix master branch and merge https://github.com/collective/collective.mailchimp/pull/40 before I can review your change. Bear with me and rebase your branch on master after I fixed it.

Please keep in mind that we currently do not officially support Plone 5.2 with c.mailchimp. Therefore it might be some work to get there...

**Comment by tisto** [comment]
@erral I just merged my fix. Plone 5.2 is an allowed failure on Travis so far: https://github.com/collective/collective.mailchimp/pull/40

It seems there is an issue with zope.schema here...

**Comment by tisto** [comment]
@erral I added a fix for zope.schema and merge master into your branch. Please check. There are still a few test failures that we would have to fix before we are able to make a Plone 5.2 compliant release. We currently do not have a client that requires this upgrade so I won't work on this myself. Though, I am more than happy to help, review and release...

**Comment by erral** [comment]
Thanks Timo, I will check it. I was working this morning on a client's site that we are preparing with 5.2, and with this changes, the product seems to work.

I will make some more tests though.

**Pull request merged**
