### PR TITLE
Use Mailchimp api 3.0 and support Plone 5

### PR DESCRIPTION
**Pull request by mauritsvanrees**
This includes work done by @jladage, @didrix and me. I myself mostly updated the testing part, though that of course led to a few fixes in the code as well.

- Instead of `postmonkey` with api 1.3 we go to the current api 3.0, without third party code.

- Plone 5 support added, although we still use the old style css registry. Kept compatibility with 4.3.  Updated Travis to test both. Default buildout now uses Plone 5.

- Replaced `mocker` with `mock`, closes issue #13.

### CODE REVIEW

**Comment by tisto** [comment]
@mauritsvanrees this is fantastic! Thank you so much for this Maurits!

**Comment by mauritsvanrees** [comment]
Thanks for reviewing and merging, @tisto.

And thanks to @jladage and @didrix for their part of the work. Guys: where we use the branch, we can now switch to master (or the release once that is done).

**Comment by tisto** [comment]
@mauritsvanrees I plan to make a new release today. Still thinking whether 1.5 or 2.0 is the correct next version.

**Comment by mauritsvanrees** [comment]
Both fine with me, but I would vote for 2.0.

**Comment by tisto** [comment]
I tend to say 2.0 as well even though existing installations should not break, right? We don't even need an upgrade step.

**Comment by mauritsvanrees** [comment]
Existing installations should be fine yes.

Well, actually you do need to visit the control panel once, to get the new information we expect. I'm not sure if visiting the portlet or the newsletter view will break before you do this. That could be an upgrade step. Or a note in the readme/changelog.

**Comment by tisto** [comment]
I will try a migration and report back...

**Comment by tisto** [comment]
@mauritsvanrees I tested the upgrade and it works fine without the need to change anything. Why would you need to add additional information? The API key is the only thing needed, right?

**Comment by mauritsvanrees** [comment]
If you have groups in a list, information is added in a different way now.

**Comment by tisto** [comment]
Would you mind writing down some notes about this, so people that upgrade know what to do? A short sentence in the README will do.

**Comment by mauritsvanrees** [comment]
I checked it. Done in 19e899f0cc131221aace41a1b3997221c80438bb.

**Comment by tisto** [comment]
@mauritsvanrees thanks!

**Pull request merged**
